apiVersion: v1
kind: Service
metadata:
  name: minha-aplicacao-service
spec:
  selector:
    app: minha-aplicacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
